Consider the two matrices
A  = [[ 1  3 -2]
      [ 0  4  7]
      [-1  2  6]]


B  = [[0 1]
     [1 3]
     [2 1]]

    
    (3,3) (3,2) 

In [16]:
import numpy as np 

A =np.matrix([[1,3,-2],[0,4,7],[-1,2,6]])
B = np.matrix([[0,1],[1,3],[2,1]])
##

print(A)
print(B)

[[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]
[[0 1]
 [1 3]
 [2 1]]


(1)	Find the component-wise sum of the matrix A with itself.

In [19]:

print(A+A)



[[ 2  6 -4]
 [ 0  8 14]
 [-2  4 12]]


(2)	Find the transpose of each of matrix A and matrix B.

In [3]:
print(A.T)
print(B.T)

[[ 1  0 -1]
 [ 3  4  2]
 [-2  7  6]]
[[0 1 2]
 [1 3 1]]


(3)	Find the inverse of matrix A.

In [4]:
print(A.I)

[[-0.52631579  1.15789474 -1.52631579]
 [ 0.36842105 -0.21052632  0.36842105]
 [-0.21052632  0.26315789 -0.21052632]]


(4)	Find the matrix product AB.

In [22]:
print (A)
print (B)
print (A*B)


[[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]
[[0 1]
 [1 3]
 [2 1]]
[[-1  8]
 [18 19]
 [14 11]]


(5)	Reshape the matrix B to be of size 2 x 3 (as opposed to its current size of 3 x 2).  Store the result as matrix C.

In [23]:
print (A)
print(np.reshape(A,(2,3)))

[[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]


ValueError: cannot reshape array of size 9 into shape (2,3)

(6)	Find the matrix product CA. 

(7)	Replace all the odd entries of matrix A with the value -1.  Store the result as matrix D.

(8)	Create a new matrix whose entries are the sums of the rows of matrix A.

(9)	Create a new matrix whose entries are the means of the columns of matrix A

(10)	Find the component-wise square root of matrix B.