In [12]:
import numpy as np 
A = np.matrix([[3,5],[7,9],[2,4]])
##

print(A)

[[3 5]
 [7 9]
 [2 4]]


(1)	Find the component-wise sum of the matrix A with itself.

(2)	Find the transpose of each of matrix A and matrix B.

In [13]:
print(A.T)

[[3 7 2]
 [5 9 4]]


(3)	Find the inverse of matrix A.

In [14]:
print(A.I)

[[-0.38095238  0.47619048 -0.5952381 ]
 [ 0.30952381 -0.26190476  0.45238095]]


(4)	Find the matrix product AB.

In [15]:
print (A)
print(np.multiply(A,A))

[[3 5]
 [7 9]
 [2 4]]
[[ 9 25]
 [49 81]
 [ 4 16]]


(5)	Reshape the matrix B to be of size 2 x 3 (as opposed to its current size of 3 x 2).  Store the result as matrix C.

In [17]:
print (A)
print( np.reshape(A,(2,3)))

[[3 5]
 [7 9]
 [2 4]]
[[3 5 7]
 [9 2 4]]


(6)	Find the matrix product CA. 

(7)	Replace all the odd entries of matrix A with the value -1.  Store the result as matrix D.

(8)	Create a new matrix whose entries are the sums of the rows of matrix A.

(9)	Create a new matrix whose entries are the means of the columns of matrix A

(10)	Find the component-wise square root of matrix B.