Consider the two matrices
A  = [[ 1  3 -2]
      [ 0  4  7]
      [-1  2  6]]


B  = [[0 1]
     [1 3]
     [2 1]]

    
    (3,3) (3,2) 

In [14]:
import numpy as np 

A =np.matrix([[1,3,-2],[0,4,7],[-1,2,6]])
B = np.matrix([[0,1],[1,3],[2,1]])
print(f"Matrix A= \n{A}\n")
print(f"Matrix B= \n{B}\n")

Matrix A= 
[[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]

Matrix B= 
[[0 1]
 [1 3]
 [2 1]]



(1)	Find the component-wise sum of the matrix A with itself.

In [15]:

print(A+A)


[[ 2  6 -4]
 [ 0  8 14]
 [-2  4 12]]


(2)	Find the transpose of each of matrix A and matrix B.

In [16]:
print(f"Matrix A before:\n{A}")
print(f"Matrix A After:\n{A.T}\n")
print(f"Matrix B before:\n{B}")
print(f"Matrix B After:\n{B.T}")
#print(A.T)
#print(B.T)

Matrix A before:
[[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]
Matrix A After:
[[ 1  0 -1]
 [ 3  4  2]
 [-2  7  6]]

Matrix B before:
[[0 1]
 [1 3]
 [2 1]]
Matrix B After:
[[0 1 2]
 [1 3 1]]


(3)	Find the inverse of matrix A.

In [17]:
print(A.I)

[[-0.52631579  1.15789474 -1.52631579]
 [ 0.36842105 -0.21052632  0.36842105]
 [-0.21052632  0.26315789 -0.21052632]]


(4)	Find the matrix product AB.

In [18]:
print ("Matrix A= \n",A)
print ("Matrix B= \n",B)
AB= A*B
print ("\nMatrix A*B= \n",AB)

Matrix A= 
 [[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]
Matrix B= 
 [[0 1]
 [1 3]
 [2 1]]

Matrix A*B= 
 [[-1  8]
 [18 19]
 [14 11]]


(5)	Reshape the matrix B to be of size 2 x 3 (as opposed to its current size of 3 x 2).  Store the result as matrix C.

In [19]:
print("Matrix B: \n",B)
C=np.reshape(B,(2,3))
print("\nMatrix C:\n",C)

Matrix B: 
 [[0 1]
 [1 3]
 [2 1]]

Matrix C:
 [[0 1 1]
 [3 2 1]]


(6)	Find the matrix product CA. 

In [20]:
print("Matrix C:\n",C)
print("Matrix A:\n",A)
CA = C.dot(A)
print("\nMatrix product of CA:\n",CA)

Matrix C:
 [[0 1 1]
 [3 2 1]]
Matrix A:
 [[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]

Matrix product of CA:
 [[-1  6 13]
 [ 2 19 14]]


(7)	Replace all the odd entries of matrix A with the value -1.  Store the result as matrix D.

In [21]:
print("Matrix A:\n",A)
D=A
D[D%2 !=0 ]=-1 
print("\n Matrix D:\n",D)         

Matrix A:
 [[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]

 Matrix D:
 [[-1 -1 -2]
 [ 0  4 -1]
 [-1  2  6]]


(8)	Create a new matrix whose entries are the sums of the rows of matrix A.

In [22]:
print("Matrix A:\n",A)
E=np.sum(A, axis=1)
print("\n Matrix E:\n",E)

Matrix A:
 [[-1 -1 -2]
 [ 0  4 -1]
 [-1  2  6]]

 Matrix E:
 [[-4]
 [ 3]
 [ 7]]


(9)	Create a new matrix whose entries are the means of the columns of matrix A

In [23]:

print("Matrix A:\n",A)
F=np.mean(A,axis=0)
print("\nThe Means of matrix A columns:\n",E)

Matrix A:
 [[-1 -1 -2]
 [ 0  4 -1]
 [-1  2  6]]

The Means of matrix A columns:
 [[-4]
 [ 3]
 [ 7]]


(10)	Find the component-wise square root of matrix B.

In [24]:

print("Matrix B:\n",B)
H=np.sqrt(B)
print("\nThe square root of matrix B:\n",B)

Matrix B:
 [[0 1]
 [1 3]
 [2 1]]

The square root of matrix B:
 [[0 1]
 [1 3]
 [2 1]]
