In [7]:
import numpy as np 

A = np.array([[1,2,3],[4,5,6]])
print (A)
print (A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
B = np.reshape(A,(3,2))
print (B) 

[[1 2]
 [3 4]
 [5 6]]


In [10]:
c =A[0,1]
print(c)

2


In [13]:
D = A[:1,:2]
print(D)

[[1 2]]


In [31]:
E= np.array([[2,4],[6,8]])
F= np.array([[1,3],[5,7]])
print(f"E array \n{E}\n")

print(f"F array \n{F}\n")


print(f"E+F arrayS \n{E+F}\n")

print(f" tis is subtract \n{np.subtract(E,F)}\n")
##
##f"counting in reverse by 4 from 2018 = {np.arange(2018,0,-4)} \n"
print(np.add(E,F))
print(np.multiply(E,F))
print(np.dot(E,F))
print(np.divide(E,F))


E array 
[[2 4]
 [6 8]]

F array 
[[1 3]
 [5 7]]

E+F arrayS 
[[ 3  7]
 [11 15]]

 tis is subtract 
[[1 1]
 [1 1]]

[[ 3  7]
 [11 15]]
[[ 2 12]
 [30 56]]
[[22 34]
 [46 74]]
[[2.         1.33333333]
 [1.2        1.14285714]]


In [33]:
print(np.mean(E,axis =0))

print (np.mean(E, axis =1))

print (np.asmatrix(F).I)
## I =  Infurse

print(np.asmatrix(F)*np.asmatrix(F).I)

[4. 6.]
[3. 7.]
[[-0.875  0.375]
 [ 0.625 -0.125]]
[[ 1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00]]


4 * 4 matrix 

In [41]:
G = np.matrix([[1,3,5,-1],[1,3,4,7],[9,3,5,-2],[1,1,2,2]])
print(G)
print(G.I)
print (E)
print(E.T)  ##  RE ARANGE

print(np.sqrt(16))

print(np.sqrt(2))
print(np.sqrt(A))




[[ 1  3  5 -1]
 [ 1  3  4  7]
 [ 9  3  5 -2]
 [ 1  1  2  2]]
[[-0.13934426  0.00819672  0.12295082  0.02459016]
 [ 0.20491803  0.81147541  0.17213115 -2.56557377]
 [ 0.08196721 -0.47540984 -0.13114754  1.57377049]
 [-0.1147541   0.06557377 -0.01639344  0.19672131]]
[[2 4]
 [6 8]]
[[2 6]
 [4 8]]
4.0
1.4142135623730951
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
